# Generated by Django 3.2.7 on 2021-12-05 23:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticuloDepartamento',
            fields=[
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('art_dep_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('art_dep_fecha_ingreso', models.DateTimeField(auto_now=True)),
                ('art_dep_nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('art_dep_estado', models.BooleanField(verbose_name='Estado')),
                ('art_dep_precio', models.PositiveIntegerField(default=0, verbose_name='Precio')),
            ],
            options={
                'verbose_name': 'Articulo Departamento',
                'verbose_name_plural': 'Articulos Departamentos',
                'db_table': 'articulo_departamento',
                'ordering': ['art_dep_id'],
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('car_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('car_nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('car_descripcion', models.CharField(max_length=150, verbose_name='Descripción')),
            ],
            options={
                'db_table': 'cargo',
            },
        ),
        migrations.CreateModel(
            name='CategoriaArticulo',
            fields=[
                ('cat_art_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cat_art_nombre', models.CharField(max_length=30, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoria Articulo',
                'verbose_name_plural': 'Categoria Articulos',
                'db_table': 'categoria_articulo',
                'ordering': ['cat_art_id'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaServicio',
            fields=[
                ('cat_ser_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cat_ser_nombre', models.CharField(max_length=15, verbose_name='Nombre')),
                ('cat_ser_descripcion', models.CharField(max_length=300, verbose_name='Descripción')),
            ],
            options={
                'db_table': 'categoria_servicio',
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('check_in_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('check_in_fecha', models.DateTimeField(auto_now=True, verbose_name='Fecha')),
                ('chek_in_observacion', models.CharField(max_length=300, verbose_name='Observación')),
            ],
            options={
                'db_table': 'check_in',
            },
        ),
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('check_out_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('check_out_fecha', models.DateTimeField(auto_now=True, verbose_name='Fecha')),
                ('check_out_observacion', models.CharField(max_length=300, verbose_name='Observación')),
                ('check_out_multas', models.PositiveIntegerField(default=0, verbose_name='Multas')),
            ],
            options={
                'db_table': 'check_out',
            },
        ),
        migrations.CreateModel(
            name='CostoDepartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cos_mensual', models.IntegerField(default=0)),
                ('cos_cant', models.IntegerField(default=0)),
                ('cos_subtotal', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'costo_departamento',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('dep_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dep_nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('dep_ubicacion', models.CharField(max_length=30, verbose_name='Ubicación')),
                ('dep_capacidad', models.PositiveIntegerField(default=0, verbose_name='Capacidad')),
                ('dep_acondicionado', models.BooleanField(verbose_name='Acondicionado')),
                ('dep_canon_renta', models.PositiveIntegerField(default=0, verbose_name='Renta')),
                ('dep_ocupacion', models.SmallIntegerField(default=1, verbose_name='Stock')),
                ('dep_estado', models.BooleanField(verbose_name='Disponibilidad')),
                ('dep_costo_mes', models.PositiveIntegerField(default=0, verbose_name='Costo Mensual')),
                ('dep_tipologia', models.CharField(max_length=10, verbose_name='Tipologia')),
                ('dep_piso', models.PositiveIntegerField(verbose_name='Piso')),
                ('dep_imagen_portada', models.ImageField(upload_to='media/departamentos', verbose_name='Portada')),
            ],
            options={
                'db_table': 'departamento',
            },
        ),
        migrations.CreateModel(
            name='DetalleCostoDepartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des_cos_fecha_ingreso', models.DateTimeField(auto_now=True)),
                ('des_cos_dep_dia', models.IntegerField(default=0, verbose_name='Costo Diario')),
                ('des_cos_dep_semanal', models.IntegerField(default=0, verbose_name='Costo Semanal')),
            ],
            options={
                'db_table': 'detalle_costo_departamento',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('fun_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fun_rut', models.CharField(max_length=10, unique=True, verbose_name='Rut')),
                ('fun_nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('fun_apellido_paterno', models.CharField(max_length=30, verbose_name='Apellido Paterno')),
                ('fun_apellido_materno', models.CharField(max_length=30, verbose_name='Apellido Materno')),
            ],
            options={
                'db_table': 'funcionario',
            },
        ),
        migrations.CreateModel(
            name='ImagenDepartamento',
            fields=[
                ('ima_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ima_departamento', models.ImageField(upload_to='media/imagenes_departamentos', verbose_name='Imagenes Departamentos')),
            ],
            options={
                'db_table': 'imagen_departamento',
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('man_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('man_fecha_creacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Creación')),
                ('man_fecha_desde', models.DateField(default=datetime.datetime.now, verbose_name='Fecha Desde')),
                ('man_fecha_hasta', models.DateField(default=datetime.datetime.now, verbose_name='Fecha Hasta')),
                ('man_cancelacion', models.BooleanField(verbose_name='Cancelar Mantenimiento')),
                ('man_observacion', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'mantenimiento',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('res_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('res_fecha_creacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Creación')),
                ('res_cantidad_huesped', models.FloatField(default=1, verbose_name='Cantidad de Huesped')),
                ('res_cantidad_diad', models.SmallIntegerField(default=1, verbose_name='Cantidad de Dias')),
                ('res_estado', models.BooleanField(default=False, verbose_name='Cancelar Reserva')),
                ('res_total', models.IntegerField(default=0, verbose_name='Total')),
                ('res_pagada', models.BooleanField(default=False, verbose_name='Reserva Pagada')),
                ('f_dep', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Servicio_Turismo_Real.departamento')),
            ],
            options={
                'db_table': 'reserva',
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('zona_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('zona_nombre', models.CharField(max_length=30, verbose_name='Nombre')),
            ],
            options={
                'db_table': 'zona',
            },
        ),
        migrations.CreateModel(
            name='DetalleServicioAdicional',
            fields=[
                ('det_ser_fecha', models.DateTimeField(auto_now=True, verbose_name='Fecha')),
                ('det_ser_total', models.IntegerField(verbose_name='Total')),
                ('pf_res', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Servicio_Turismo_Real.reserva')),
            ],
            options={
                'db_table': 'detalle_servicio_adicional',
            },
        ),
        migrations.CreateModel(
            name='InventarioDepartamento',
            fields=[
                ('pf_dep', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Servicio_Turismo_Real.departamento')),
                ('inv_dep_cantidad', models.FloatField(verbose_name='Cantidad')),
                ('inv_dep_costo', models.IntegerField(verbose_name='Costo')),
            ],
            options={
                'db_table': 'inventario_departamento',
            },
        ),
        migrations.CreateModel(
            name='ServicioAdicional',
            fields=[
                ('ser_adi_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ser_adi_nombre', models.CharField(max_length=300, verbose_name='Nombre')),
                ('ser_adi_precio', models.FloatField(verbose_name='Precio')),
                ('f_cat_ser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Servicio_Turismo_Real.categoriaservicio')),
            ],
            options={
                'db_table': 'servicio_adicional',
            },
        ),
    ]
