# Generated by Django 3.2.7 on 2021-09-21 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticuloDepartamento',
            fields=[
                ('art_dep_id', models.IntegerField(primary_key=True, serialize=False)),
                ('art_dep_fecha_ingreso', models.DateField()),
                ('art_dep_nombre', models.CharField(max_length=30)),
                ('art_dep_estado', models.CharField(max_length=1)),
                ('art_dep_precio', models.IntegerField()),
            ],
            options={
                'db_table': 'articulo_departamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('car_id', models.IntegerField(primary_key=True, serialize=False)),
                ('car_nombre', models.CharField(max_length=30)),
                ('car_descripcion', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'cargo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriaArticulo',
            fields=[
                ('cat_art_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cat_art_nombre', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'categoria_articulo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriaServicio',
            fields=[
                ('cat_ser_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cat_ser_nombre', models.CharField(max_length=15)),
                ('cat_ser_descripcion', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'categoria_servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('check_in_id', models.IntegerField(primary_key=True, serialize=False)),
                ('check_in_fecha', models.DateField()),
                ('chek_in_observacion', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'check_in',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('check_out_id', models.IntegerField(primary_key=True, serialize=False)),
                ('check_out_fecha', models.DateField()),
                ('check_out_observacion', models.CharField(max_length=300)),
                ('check_out_multas', models.IntegerField()),
            ],
            options={
                'db_table': 'check_out',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cli_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cli_rut', models.IntegerField()),
                ('cli_rut_df', models.CharField(max_length=1)),
                ('cli_nombre', models.CharField(max_length=30)),
                ('cli_apellido_paterno', models.CharField(max_length=10)),
                ('cli_apellido_materno', models.CharField(max_length=10)),
                ('cli_numero_contacto', models.IntegerField()),
                ('cli_ciudad', models.CharField(max_length=30)),
                ('cli_comuna', models.CharField(max_length=30)),
                ('cli_direccion', models.CharField(max_length=30)),
                ('cli_email', models.CharField(max_length=30)),
                ('cli_password', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('dep_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dep_nombre', models.CharField(max_length=30)),
                ('dep_ubicacion', models.CharField(max_length=30)),
                ('dep_capacidad', models.BooleanField()),
                ('dep_acondicionado', models.CharField(max_length=1)),
                ('dep_canon_renta', models.IntegerField()),
                ('dep_estado', models.CharField(max_length=1)),
                ('dep_costo_mes', models.IntegerField()),
            ],
            options={
                'db_table': 'departamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('fun_id', models.IntegerField(primary_key=True, serialize=False)),
                ('fun_rut', models.FloatField()),
                ('fun_rut_df', models.CharField(max_length=1)),
                ('fun_nombre', models.CharField(max_length=30)),
                ('fun_apellido_paterno', models.CharField(max_length=30)),
                ('fun_apellido_materno', models.CharField(max_length=30)),
                ('fun_cargo', models.CharField(max_length=30)),
                ('fun_usuario', models.CharField(max_length=30)),
                ('fun_password', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'funcionario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImagenDepartamento',
            fields=[
                ('ima_id', models.FloatField(primary_key=True, serialize=False)),
                ('ima_departamento', models.BinaryField()),
            ],
            options={
                'db_table': 'imagen_departamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('man_id', models.IntegerField(primary_key=True, serialize=False)),
                ('man_fecha_creacion', models.DateField()),
                ('man_fecha_desde', models.DateField()),
                ('man_fecha_hasta', models.DateField()),
                ('man_fecha_cancelacion', models.DateField()),
                ('man_observacion', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'mantenimiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('res_id', models.IntegerField(primary_key=True, serialize=False)),
                ('res_fecha', models.DateField()),
                ('res_fecha_creacion', models.DateField()),
                ('res_cantidad_huesped', models.FloatField()),
                ('res_fecha_desde', models.DateField()),
                ('res_fecha_hasta', models.DateField()),
                ('res_fecha_cancelacion', models.DateField()),
                ('res_total', models.IntegerField()),
                ('res_pagada', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'reserva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServicioAdicional',
            fields=[
                ('ser_adi_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ser_adi_nombre', models.CharField(max_length=300)),
                ('ser_adi_precio', models.FloatField()),
            ],
            options={
                'db_table': 'servicio_adicional',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('zona_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'zona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleCostoDepartamento',
            fields=[
                ('des_cos_dep_dia', models.IntegerField()),
                ('des_cos_dep_semanal', models.IntegerField()),
                ('pf_dep', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='arriendo_departamento.departamento')),
            ],
            options={
                'db_table': 'detalle_costo_departamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleServicioAdicional',
            fields=[
                ('det_ser_fecha', models.DateField()),
                ('det_ser_total', models.IntegerField()),
                ('pf_res', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='arriendo_departamento.reserva')),
            ],
            options={
                'db_table': 'detalle_servicio_adicional',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventarioDepartamento',
            fields=[
                ('pf_dep', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='arriendo_departamento.departamento')),
                ('inv_dep_catidad', models.FloatField()),
                ('inv_dep_costo', models.IntegerField()),
            ],
            options={
                'db_table': 'inventario_departamento',
                'managed': False,
            },
        ),
    ]
