# Generated by Django 3.2.7 on 2021-10-19 15:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('car_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('car_nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('car_descripcion', models.CharField(max_length=150, verbose_name='Descripción')),
            ],
            options={
                'db_table': 'cargo',
            },
        ),
        migrations.CreateModel(
            name='CategoriaArticulo',
            fields=[
                ('cat_art_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cat_art_nombre', models.CharField(max_length=30, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoria Articulo',
                'verbose_name_plural': 'Categoria Articulos',
                'db_table': 'categoria_articulo',
                'ordering': ['cat_art_id'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaServicio',
            fields=[
                ('cat_ser_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cat_ser_nombre', models.CharField(max_length=15, verbose_name='Nombre')),
                ('cat_ser_descripcion', models.CharField(max_length=300, verbose_name='Descripción')),
            ],
            options={
                'db_table': 'categoria_servicio',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('dep_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dep_nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('dep_ubicacion', models.CharField(max_length=30, verbose_name='Ubicación')),
                ('dep_capacidad', models.IntegerField(verbose_name='Capacidad')),
                ('dep_acondicionado', models.BooleanField(verbose_name='Acondicionado')),
                ('dep_canon_renta', models.PositiveIntegerField(default=0, verbose_name='Renta')),
                ('dep_estado', models.BooleanField(verbose_name='Estado')),
                ('dep_costo_mes', models.PositiveIntegerField(default=0, verbose_name='Costo Mensual')),
                ('dep_tipologia', models.CharField(max_length=5, verbose_name='Tipologia')),
                ('dep_piso', models.PositiveIntegerField(verbose_name='Piso')),
                ('dep_imagen_portada', models.ImageField(upload_to='media/departamentos', verbose_name='Portada')),
            ],
            options={
                'db_table': 'departamento',
            },
        ),
        migrations.CreateModel(
            name='UserUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=128, null=True, verbose_name='Contraseña')),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Nombre de Usuario')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('rut', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='Rut')),
                ('apellido_paterno', models.CharField(blank=True, max_length=30, null=True, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(blank=True, max_length=30, null=True, verbose_name='Apellido Materno')),
                ('numero_contacto', models.IntegerField(blank=True, null=True, verbose_name='Numero de Contacto')),
                ('direccion', models.CharField(blank=True, max_length=30, null=True, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('zona_id', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Nombre')),
            ],
            options={
                'db_table': 'zona',
            },
        ),
        migrations.CreateModel(
            name='DetalleCostoDepartamento',
            fields=[
                ('des_cos_dep_dia', models.IntegerField(verbose_name='Costo Diario')),
                ('des_cos_dep_semanal', models.IntegerField(verbose_name='Costo Semanal')),
                ('pf_dep', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Servicio_Turismo_Real.departamento')),
            ],
            options={
                'db_table': 'detalle_costo_departamento',
            },
        ),
        migrations.CreateModel(
            name='ServicioAdicional',
            fields=[
                ('ser_adi_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ser_adi_nombre', models.CharField(max_length=300, verbose_name='Nombre')),
                ('ser_adi_precio', models.FloatField(verbose_name='Precio')),
                ('f_cat_ser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Servicio_Turismo_Real.categoriaservicio')),
            ],
            options={
                'db_table': 'servicio_adicional',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('res_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('res_fecha_creacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Creación')),
                ('res_cantidad_huesped', models.FloatField(verbose_name='Cantidad de Huesped:')),
                ('res_fecha_desde', models.DateField(default=datetime.datetime.now, verbose_name='Fecha Desde:')),
                ('res_fecha_hasta', models.DateField(default=datetime.datetime.now, verbose_name='Fecha Hasta:')),
                ('res_cancelacion', models.BooleanField(verbose_name='Cancelar Reserva:')),
                ('res_total', models.IntegerField(verbose_name='Total:')),
                ('res_pagada', models.BooleanField(verbose_name='Reserva Pagada:')),
                ('f_cli', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Servicio_Turismo_Real.useruser')),
                ('f_dep', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Servicio_Turismo_Real.departamento')),
            ],
            options={
                'db_table': 'reserva',
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('man_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('man_fecha_creacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Creación')),
                ('man_fecha_desde', models.DateField(default=datetime.datetime.now, verbose_name='Fecha Desde')),
                ('man_fecha_hasta', models.DateField(default=datetime.datetime.now, verbose_name='Fecha Hasta')),
                ('man_cancelacion', models.BooleanField(verbose_name='Cancelar Mantenimiento')),
                ('man_observacion', models.CharField(max_length=300)),
                ('f_dep', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Servicio_Turismo_Real.departamento')),
            ],
            options={
                'db_table': 'mantenimiento',
            },
        ),
        migrations.CreateModel(
            name='ImagenDepartamento',
            fields=[
                ('ima_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ima_departamento', models.ImageField(upload_to='media/imagenes_departamentos', verbose_name='Imagenes Departamentos')),
                ('f_dep', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Servicio_Turismo_Real.departamento')),
            ],
            options={
                'db_table': 'imagen_departamento',
            },
        ),
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('fun_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fun_rut', models.CharField(max_length=10, unique=True, verbose_name='Rut')),
                ('fun_nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('fun_apellido_paterno', models.CharField(max_length=30, verbose_name='Apellido Paterno')),
                ('fun_apellido_materno', models.CharField(max_length=30, verbose_name='Apellido Materno')),
                ('f_car', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Servicio_Turismo_Real.cargo', verbose_name='Categoria')),
            ],
            options={
                'db_table': 'funcionarios',
            },
        ),
        migrations.AddField(
            model_name='departamento',
            name='f_zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Servicio_Turismo_Real.zona', verbose_name='Zona'),
        ),
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('check_out_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('check_out_fecha', models.DateTimeField(auto_now=True, verbose_name='Fecha')),
                ('check_out_observacion', models.CharField(max_length=300, verbose_name='Observación')),
                ('check_out_multas', models.PositiveIntegerField(default=0, verbose_name='Multas')),
                ('f_fun', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Servicio_Turismo_Real.funcionarios')),
                ('f_res', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Servicio_Turismo_Real.reserva')),
            ],
            options={
                'db_table': 'check_out',
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('check_in_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('check_in_fecha', models.DateTimeField(auto_now=True, verbose_name='Fecha')),
                ('chek_in_observacion', models.CharField(max_length=300, verbose_name='Observación')),
                ('f_fun', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Servicio_Turismo_Real.funcionarios')),
                ('f_res', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Servicio_Turismo_Real.reserva')),
            ],
            options={
                'db_table': 'check_in',
            },
        ),
        migrations.CreateModel(
            name='ArticuloDepartamento',
            fields=[
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('art_dep_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('art_dep_fecha_ingreso', models.DateTimeField(auto_now=True)),
                ('art_dep_nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('art_dep_estado', models.BooleanField(verbose_name='Estado')),
                ('art_dep_precio', models.PositiveIntegerField(default=0, verbose_name='Precio')),
                ('f_cat_art', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Servicio_Turismo_Real.categoriaarticulo', verbose_name='Categoria')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicio_turismo_real_articulodepartamento_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicio_turismo_real_articulodepartamento_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Articulo Departamento',
                'verbose_name_plural': 'Articulos Departamentos',
                'db_table': 'articulo_departamento',
                'ordering': ['art_dep_id'],
            },
        ),
        migrations.CreateModel(
            name='InventarioDepartamento',
            fields=[
                ('pf_dep', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Servicio_Turismo_Real.departamento')),
                ('inv_dep_cantidad', models.FloatField(verbose_name='Cantidad')),
                ('inv_dep_costo', models.IntegerField(verbose_name='Costo')),
                ('pf_art_dep', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Servicio_Turismo_Real.articulodepartamento')),
            ],
            options={
                'db_table': 'inventario_departamento',
                'unique_together': {('pf_dep', 'pf_art_dep')},
            },
        ),
        migrations.CreateModel(
            name='DetalleServicioAdicional',
            fields=[
                ('det_ser_fecha', models.DateTimeField(auto_now=True, verbose_name='Fecha')),
                ('det_ser_total', models.IntegerField(verbose_name='Total')),
                ('pf_res', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Servicio_Turismo_Real.reserva')),
                ('pf_ser_adi', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Servicio_Turismo_Real.servicioadicional')),
            ],
            options={
                'db_table': 'detalle_servicio_adicional',
                'unique_together': {('pf_res', 'pf_ser_adi')},
            },
        ),
    ]
