# Generated by Django 3.2.7 on 2021-10-19 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Servicio_Turismo_Real', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('fun_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fun_rut', models.CharField(max_length=10, unique=True, verbose_name='Rut')),
                ('fun_nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('fun_apellido_paterno', models.CharField(max_length=30, verbose_name='Apellido Paterno')),
                ('fun_apellido_materno', models.CharField(max_length=30, verbose_name='Apellido Materno')),
                ('f_car', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Servicio_Turismo_Real.cargo', verbose_name='Categoria')),
            ],
            options={
                'db_table': 'funcionario',
            },
        ),
        migrations.AlterField(
            model_name='checkin',
            name='f_fun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Servicio_Turismo_Real.funcionario'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='f_fun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Servicio_Turismo_Real.funcionario'),
        ),
        migrations.DeleteModel(
            name='Funcionarios',
        ),
    ]
