# Generated by Django 3.2.7 on 2021-10-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicio_Turismo_Real', '0002_auto_20211019_1240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useruser',
            options={'ordering': ['id'], 'permissions': (('is_funcionario', 'Is Funcionario'), ('is_cliente', 'Is Cliente')), 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='departamento',
            name='dep_capacidad',
            field=models.PositiveIntegerField(default=0, verbose_name='Capacidad'),
        ),
    ]
