# Generated by Django 3.2.7 on 2021-10-23 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Servicio_Turismo_Real', '0003_auto_20211022_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='departamento',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='departamento',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicio_turismo_real_departamento_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='departamento',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicio_turismo_real_departamento_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicio_turismo_real_funcionario_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicio_turismo_real_funcionario_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
