# Generated by Django 3.2.7 on 2021-10-09 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='numero_contacto',
            field=models.IntegerField(blank=True, null=True, verbose_name='Telefono Contacto'),
        ),
    ]
